[package]
name = "hammer_font"
version = "0.1.0"
edition = "2024"

[dependencies]
freetype-rs = "0.38.0"
freetype-sys = { version = "0.23.0", features = ["bundled"] }
image = "0.25.8"
texture_packer = "0.30.0"
csv = "1.3.1"
egui = "0.32.3"